# Generated by Django 4.2.30 on 2026-05-01 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_short_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.CharField(choices=[('ksara', 'كسارة'), ('mixer', 'ميكسر'), ('makbs', 'مكبس'), ('hala', 'حلة استاندرد'), ('table1', 'ترابيزة'), ('troly1', 'ترولي لانشون'), ('troly2', 'ترولي صاجات'), ('qalep', 'قالب لانشون')], max_length=50, verbose_name='نوع المنتج')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^01\\d{9}$', 'رقم موبايل مصري غير صحيح')], verbose_name='الموبايل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='الإيميل')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='الشركة')),
                ('message', models.TextField(verbose_name='الطلب')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('quoted', 'تم عرض السعر'), ('accepted', 'تم القبول'), ('rejected', 'تم الرفض')], default='new', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'طلب عرض سعر',
                'verbose_name_plural': 'طلبات عروض الأسعار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='QuoteRequest',
        ),
    ]
